apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-lab.fullname" . }}-index-html-pink
  labels:
    {{- include "nginx-lab.labels" . | nindent 4 }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to nginx!</title>
    <style>
    html { color-scheme: light dark; }
    body { width: 35em; margin: 0 auto;
    font-family: Tahoma, Verdana, Arial, sans-serif; 
    background-color: pink; }
    </style>
    </head>
    <body>
    <h1>{{ (split "-" (include "nginx-lab.fullname" .))._0 }} is up and online!</h1>
    <p>If you see this page, the nginx test web server application for blog articles on amayacitta.co.uk
    is running successfully. Well done.</p>

    <p>Switch to the root application <a href="/">here</a>.<br/>
    </p>

    <p>Switch to the pink application <a href="/pink/">here</a>.<br/>
    </p>

    <p>Switch to the blue application <a href="/blue/">here</a>.<br/>
    </p>

    <p>Switch to the green application <a href="/green/">here</a>.<br/>
    </p>

    <p>For online documentation and support please refer to
    <a href="https://amayacitta.co.uk">amayacitta.co.uk</a>.<br/>
    </p>

    {{- if .Values.HostRule.enabled -}}
    <p>
    Other aliases configured for this application are:<br/>
    {{- range slice .Values.hostnames 1 }}
      <a href="https://{{ . }}">{{ . }}</a><br/>
    {{- end }}
    </p>
    {{- end }}

    <p><em>Thank you for using nginx.</em></p>
    </body>
    </html>