apiVersion: v1
kind: Secret
metadata:
  name: avi-amko-token
  namespace: avi-system
  annotations:
    kubernetes.io/service-account.name: "avi-amko-sa"
type: kubernetes.io/service-account-token